name: projrapidapi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"

flutter:

  uses-material-design: true
  assets:
    - assets/ic_launcher.png
